# Generated by Django 5.0.6 on 2024-07-03 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='vertical',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=2024, on_delete=django.db.models.deletion.CASCADE, to='cafe.category'),
            preserve_default=False,
        ),
    ]
