# Generated by Django 5.0.6 on 2024-07-03 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_category_remove_product_vertical_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cake', 'کیک'), ('Hot Drink', 'نوشیدنی گرم'), ('Cold Drink', 'نوشیدنی سرد'), ('Breakfast', 'صبحانه')], max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='vertical',
            field=models.ForeignKey(default=2024, on_delete=django.db.models.deletion.CASCADE, to='cafe.vertical'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
